SELECT * FROM IMAGE;

SELECT
  MIN(HEIGHT) MINHEIGHT, AVG(HEIGHT) AVGHEIGHT, STDDEV_POP(HEIGHT) STDHEIGHT, MAX(HEIGHT) MAXHEIGHT,
  MIN(WIDTH) MINWIDTH, AVG(WIDTH) AVGWIDTH, STDDEV_POP(WIDTH) STDWIDTH, MAX(WIDTH) MAXWIDTH
FROM IMAGE;

SELECT COUNT(*) FROM IMAGE;